## PRIMER ARCHIVO

In [12]:
df = pd.read_csv('beer_reviews.csv')
df

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1586609,14359,The Defiant Brewing Company,1162684892,5.0,4.0,3.5,maddogruss,Pumpkin Ale,4.0,4.0,The Horseman's Ale,5.2,33061
1586610,14359,The Defiant Brewing Company,1161048566,4.0,5.0,2.5,yelterdow,Pumpkin Ale,2.0,4.0,The Horseman's Ale,5.2,33061
1586611,14359,The Defiant Brewing Company,1160702513,4.5,3.5,3.0,TongoRad,Pumpkin Ale,3.5,4.0,The Horseman's Ale,5.2,33061
1586612,14359,The Defiant Brewing Company,1160023044,4.0,4.5,4.5,dherling,Pumpkin Ale,4.5,4.5,The Horseman's Ale,5.2,33061
1586613,14359,The Defiant Brewing Company,1160005319,5.0,4.5,4.5,cbl2,Pumpkin Ale,4.5,4.5,The Horseman's Ale,5.2,33061

In [3]:
df1 = pd.read_csv('russian_alcohol_consumption.csv')
df1

,year,region,wine,beer,vodka,champagne,brandy
0,1998,Republic of Adygea,1.9,8.8,3.4,0.3,0.1
1,1998,Altai Krai,3.3,19.2,11.3,1.1,0.1
2,1998,Amur Oblast,2.1,21.2,17.3,0.7,0.4
3,1998,Arkhangelsk Oblast,4.3,10.6,11.7,0.4,0.3
4,1998,Astrakhan Oblast,2.9,18.0,9.5,0.8,0.2
...,...,...,...,...,...,...,...
1610,2016,Chuvash Republic,5.0,42.3,7.7,0.7,0.4
1611,2016,Chukotka Autonomous Okrug,3.9,34.0,11.6,1.8,1.1
1612,2016,Sakha (Yakutia) Republic,4.3,56.1,8.2,1.8,0.5
1613,2016,Yamalo-Nenets Autonomous Okrug,4.5,75.8,8.2,1.7,1.3
1614,2016,Yaroslavl Oblast,10.2,38.0,8.9,1.4,1.0

In [7]:
df2 = pd.read_csv('open_units.csv')
df2

,index,Product,Brand,Category,Style,Quantity,Quantity Units,Volume,Package,ABV,Units of Alcohol,Units (4 Decimal Places),Units per 100ml
0,0,13 Guns,Crafty Dan,Beer,IPA,330,ml,330,bottle,5.5,1.8,1.8150,0.55
1,1,13 Guns,Crafty Dan,Beer,IPA,330,ml,330,can,5.5,1.8,1.8150,0.55
2,2,13 Guns,Crafty Dan,Beer,IPA,1,pint,568,draught,5.5,3.1,3.1240,0.55
3,3,Abbot Ale,Greene King,Beer,Ale,500,ml,500,bottle,5.0,2.5,2.5000,0.50
4,4,Abbot Ale,Greene King,Beer,Beer,1,pint,568,draught,5.0,2.8,2.8400,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,1077,Yeastie Boys White Noise,Yeastie Boys,Beer,Wheat Beer,330,ml,330,can,4.4,1.5,1.4520,0.44
1078,1078,Young's Bitter,Young's,Beer,Bitter,1,pint,568,draught,3.7,2.1,2.1016,0.37
1079,1079,Young's London Stout,Young's,Beer,Stout,1,pint,568,draught,4.3,2.4,2.4424,0.43
1080,1080,Zeffer Hopped Infused Cider,Zeffer,Cider,NaN,330,ml,330,bottle,5.4,1.8,1.7820,0.54
1081,1081,Zywiec,Zywiec,Beer,Lager,500,ml,500,bottle,5.6,2.8,2.8000,0.56

In [9]:
df3 = pd.read_csv('liquor.csv')
df3

,date,convenience_store,store,name,address,city,zipcode,store_location,county_number,county,...,vendor_no,vendor,item,description,pack,liter_size,state_btl_cost,btl_price,bottle_qty,total
0,2015-02-19,NaN,2190,"Central City Liquor, Inc.",1460 2ND AVE,DES MOINES,50314,1460 2ND AVE\nDES MOINES 50314\n(41.6055703350...,77,Polk,...,421,"Sazerac Co., Inc.",64858,Fireball Cinnamon Whiskey Mini Dispenser,1,3000,29.72,44.58,6,267.48
1,2015-02-09,NaN,2190,"Central City Liquor, Inc.",1460 2ND AVE,DES MOINES,50314,1460 2ND AVE\nDES MOINES 50314\n(41.6055703350...,77,Polk,...,421,"Sazerac Co., Inc.",64858,Fireball Cinnamon Whiskey Mini Dispenser,1,3000,29.72,44.58,5,222.90
2,2014-10-30,NaN,2190,Central City Liquor Inc.,1460 2ND AVE,DES MOINES,50314,1460 2ND AVE\nDES MOINES 50314\n(41.6055703350...,77,Polk,...,421,Sazerac Co. Inc.,64858,Fireball Cinnamon Whiskey Mini Dispenser,1,3000,29.72,44.58,6,267.48
3,2014-02-27,NaN,2190,Central City Liquor Inc.,1460 2ND AVE,DES MOINES,50314,1460 2ND AVE\nDES MOINES 50314\n(41.6055703350...,77,Polk,...,421,Sazerac Co. Inc.,64858,Fireball Cinnamon Whiskey Mini Dispenser,1,3000,29.72,44.58,1,44.58
4,2014-02-25,NaN,2190,Central City Liquor Inc.,1460 2ND AVE,DES MOINES,50314,1460 2ND AVE\nDES MOINES 50314\n(41.6055703350...,77,Polk,...,421,Sazerac Co. Inc.,64858,Fireball Cinnamon Whiskey Mini Dispenser,1,3000,29.72,44.58,1,44.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,2014-02-12,NaN,2508,Hy-vee Food Store #1/ceda,1843 JOHNSON AVENUE N.W.,CEDAR RAPIDS,52405,1843 JOHNSON AVENUE N.W.\nCEDAR RAPIDS 52405\n...,57,Linn,...,395,Proximo,58868,Jose Cuervo Authentic Strawberry Margarita,6,1750,8.20,12.30,18,221.40
14996,2014-09-09,NaN,2508,Hy-Vee Food Store #1 / Cedar Rapids,1843 JOHNSON AVENUE N.W.,CEDAR RAPIDS,52405,1843 JOHNSON AVENUE N.W.\nCEDAR RAPIDS 52405\n...,57,Linn,...,395,Proximo,58872,Jose Cuervo Authentic Light Margarita Lime,6,1750,8.20,12.30,6,73.80
14997,2014-02-12,NaN,2508,Hy-vee Food Store #1/ceda,1843 JOHNSON AVENUE N.W.,CEDAR RAPIDS,52405,1843 JOHNSON AVENUE N.W.\nCEDAR RAPIDS 52405\n...,57,Linn,...,395,Proximo,58873,Jose Cuervo Authentic Watermelon Margarita,6,1750,8.20,12.30,12,147.60
14998,2014-01-08,NaN,2508,Hy-vee Food Store #1/ceda,1843 JOHNSON AVENUE N.W.,CEDAR RAPIDS,52405,1843 JOHNSON AVENUE N.W.\nCEDAR RAPIDS 52405\n...,57,Linn,...,395,Proximo,58875,Jose Cuervo Golden Margarita,6,1750,10.50,15.74,6,94.44
14999,2014-03-12,NaN,2508,Hy-vee Food Store #1/Cedar Rapids,1843 JOHNSON AVENUE N.W.,CEDAR RAPIDS,52405,1843 JOHNSON AVENUE N.W.\nCEDAR RAPIDS 52405\n...,57,Linn,...,395,Proximo,58875,Jose Cuervo Golden Margarita,6,1750,9.50,14.74,12,176.88